### ISSUE TITLE
Bad Link on Shows Page

### ISSUE THREAD

**Issue by ityler** [wesbos/Syntax#10]
Link to Scott's webpage is bad. Works by adding "www." or by forcing "http" over "https" and relying on the redirect to correctly reroute.

**Comment by stolinski** [comment]
Fixed in https://github.com/wesbos/Syntax/commit/42df32697990bb70431308335d12d77a542be646

If you clear your cache, leveluptutorials.com will correctly redirect to www. The issue is browser cached to be https://leveluptutorials.com which isn't throwing a redirect due to these restrictions: https://support.dnsimple.com/articles/redirector-https

The solution would be to have a custom redirect server running on https. Either way, I've updated the links.

**Comment by ityler** [comment]
@stolinski Ah thanks for taking the fix, I guess I'll close the pull request I made then. Interesting I was having the problem even though I had never been to either site before in the past. Not sure exactly how you are doing redirects but in my case I would rewrite the URL in apache mod_rewrite.

**Comment by stolinski** [comment]
Oh, I see now that the links were using https.

Unfortunately, I'm hosting on a platform that doesn't give me that kind of control without firing up another container. I could point the domain to an apache server or node server that handles the redirect... maybe a lambda function would do the trick.

**Comment by ityler** [comment]
Just to clarify, so the expected behavior of leveluptutorials.com is for the connection to be refused(die) in the event "www" is not included in the URL? Even with my cache cleared I am still not being redirected with the URL of (https://leveluptotorials.com)

**Comment by stolinski** [comment]
It's because of the https which isn't supported. If you were to have http://leveluptutorials it would properly redirect. That is currently the expected behavior although I should have a better solution working today.

**Comment by stolinski** [comment]
FYI, I setup an nginx redirect server for https://leveluptutorials.com all seems to be working now.
